# Generated by Django 4.2 on 2023-05-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0002_alter_cars_modelyear_alter_cars_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
