# Generated by Django 4.2 on 2023-06-01 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CarApp', '0004_cars_colour_cars_customer_cars_enginetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='customer',
            field=models.ManyToManyField(related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
